name: FlintAndSteelPlus
version: '1.0a'
main: dev.bluenightfury46.flinatandsteelplus.flintandsteel
api-version: '1.21'
authors: [ BlueNightFury46 ]
description: Adds a better flint and steel
website: bluenightfury46.dev
